name: WatchaPedia Development Server CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: ✔️ checkout
        uses: actions/checkout@v3

      - name: ✔️ set JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ✔️ create application.yml
        run: |
          cd ./src/main
          mkdir resources && cd $_
          echo "$APPLICATION" > ./application.yml
        env:
          APPLICATION: ${{ secrets.APPLICATION }}

      - name: ✔️ set permission
        run: chmod +x gradlew

      - name: ✔️️ gradle build
        run: ./gradlew clean build --exclude-task test

      - name: ✔️ docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ✔️ docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .

      - name: ✔️ push to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

  cd:
    needs: ci

    runs-on: ubuntu-latest

    steps:
      - name: ✔️ checkout
        uses: actions/checkout@v3

      - name: ✔️ deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker stop ${{ secrets.DOCKER_IMAGE }}
            sudo docker rm ${{ secrets.DOCKER_IMAGE }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
            sudo docker run -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
            --name ${{ secrets.DOCKER_IMAGE }} \
            -d ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
